title: Why am I here 
author: Stop looking at me
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Sorry were out of Sprite is 7up ok?

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
